version: '3'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: rootp
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "81:80"
        depends_on:
            - db
        networks:
            - elf-teamllist
    app:
        build:
            context: .

            args:
                uid: ${UID}
        working_dir: /var/www/html
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - elf-teamllist
    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - .:/var/www/html
            - .:/etc/nginx/elf.conf
        networks:
            - elf-teamllist
    networks:
        elf-teamllist:
            driver: bridge        
